app.name=LoginMVC
db.host=localhost
db.port=3306
db.name=loginmvc_db
db.user=root
db.password=mabrouk123
db.options=createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
